package compiler

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestNewCompiler(t *testing.T) {
	comp := NewCompiler(t.TempDir())
	if comp == nil {
		t.Fatal("NewCompiler returned nil")
	}
	if comp.LibraryManager == nil {
		t.Error("LibraryManager is nil")
	}
	if comp.Resolver == nil {
		t.Error("Resolver is nil")
	}
}

func TestCompile_BasicSpec(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "app.spec.promptc")
	content := `features:
  - hello: "World"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	outPath, err := comp.Compile(specFile, nil)
	if err != nil {
		t.Fatalf("Compile failed: %v", err)
	}
	if outPath == "" {
		t.Fatal("Compile returned empty output path")
	}

	data, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("failed to read output: %v", err)
	}
	out := string(data)
	if !strings.Contains(out, "Generated by promptc") {
		t.Error("output missing metadata header")
	}
	if !strings.Contains(out, "World") {
		t.Error("output missing feature content")
	}
}

func TestCompile_OutputDir(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "myapp.spec.promptc")
	content := `features:
  - f: "test"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	outDir := filepath.Join(dir, "custom-output")
	comp := NewCompiler(dir)
	outPath, err := comp.Compile(specFile, &CompileOptions{OutputDir: outDir})
	if err != nil {
		t.Fatalf("Compile failed: %v", err)
	}

	expected := filepath.Join(outDir, "instructions.promptc")
	if outPath != expected {
		t.Errorf("output path = %q, want %q", outPath, expected)
	}
	if _, err := os.Stat(expected); os.IsNotExist(err) {
		t.Error("output file was not created")
	}
}

func TestCompile_DefaultOutputDirName(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "coffeeshop.spec.promptc")
	content := `features:
  - f: "test"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	outPath, err := comp.Compile(specFile, nil)
	if err != nil {
		t.Fatalf("Compile failed: %v", err)
	}

	// default output dir should strip .spec.promptc
	wantDir := filepath.Join(dir, "coffeeshop")
	wantPath := filepath.Join(wantDir, "instructions.promptc")
	if outPath != wantPath {
		t.Errorf("output path = %q, want %q", outPath, wantPath)
	}
}

func TestCompile_WithImports(t *testing.T) {
	dir := t.TempDir()

	promptsDir := filepath.Join(dir, "prompts")
	if err := os.MkdirAll(promptsDir, 0755); err != nil {
		t.Fatal(err)
	}
	libContent := "# My Library\nSome guidelines here."
	if err := os.WriteFile(filepath.Join(promptsDir, "mylib.prompt"), []byte(libContent), 0644); err != nil {
		t.Fatal(err)
	}

	specFile := filepath.Join(dir, "app.spec.promptc")
	content := `imports:
  - mylib
features:
  - f: "test"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	outPath, err := comp.Compile(specFile, nil)
	if err != nil {
		t.Fatalf("Compile failed: %v", err)
	}

	data, _ := os.ReadFile(outPath)
	if !strings.Contains(string(data), "My Library") {
		t.Error("output missing imported library content")
	}
}

func TestCompile_ValidationError(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "bad.spec.promptc")
	content := `unknown_key: value
features:
  - f: "test"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	_, err := comp.Compile(specFile, nil)
	if err == nil {
		t.Fatal("expected validation error, got nil")
	}
	if !strings.Contains(err.Error(), "validation failed") {
		t.Errorf("error should mention validation: %v", err)
	}
}

func TestCompile_SkipValidate(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "lax.spec.promptc")
	content := `unknown_key: value
features:
  - f: "test"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	_, err := comp.Compile(specFile, &CompileOptions{SkipValidate: true})
	if err != nil {
		t.Errorf("expected no error with SkipValidate=true, got: %v", err)
	}
}

func TestCompile_FileNotFound(t *testing.T) {
	comp := NewCompiler(t.TempDir())
	_, err := comp.Compile("/nonexistent/path.spec.promptc", nil)
	if err == nil {
		t.Fatal("expected error for missing file")
	}
}

func TestCompile_InvalidYAML(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "bad.spec.promptc")
	content := `invalid: yaml: here: [`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	_, err := comp.Compile(specFile, nil)
	if err == nil {
		t.Fatal("expected error for invalid YAML")
	}
}

func TestParseSpec_Resources(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "res.spec.promptc")
	content := `features:
  - f: "test"
resources:
  - url: "https://example.com/docs"
    name: example-docs
  - git: "https://github.com/org/repo"
    name: ref-repo
    ref: main
    path: docs/
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	spec, err := comp.ParseSpec(specFile)
	if err != nil {
		t.Fatalf("ParseSpec failed: %v", err)
	}

	if len(spec.Resources) != 2 {
		t.Fatalf("expected 2 resources, got %d", len(spec.Resources))
	}
	if spec.Resources[0].URL != "https://example.com/docs" {
		t.Errorf("wrong URL: %q", spec.Resources[0].URL)
	}
	if spec.Resources[1].Git != "https://github.com/org/repo" {
		t.Errorf("wrong Git: %q", spec.Resources[1].Git)
	}
	if spec.Resources[1].Ref != "main" {
		t.Errorf("wrong Ref: %q", spec.Resources[1].Ref)
	}
}

func TestParseSpec_Build(t *testing.T) {
	dir := t.TempDir()
	specFile := filepath.Join(dir, "build.spec.promptc")
	content := `features:
  - f: "test"
build:
  agent:
    command: claude
    args:
      - "--dangerously-skip-permissions"
  sandbox:
    type: docker
    image: "ubuntu:22.04"
`
	if err := os.WriteFile(specFile, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	comp := NewCompiler(dir)
	spec, err := comp.ParseSpec(specFile)
	if err != nil {
		t.Fatalf("ParseSpec failed: %v", err)
	}

	if spec.Build == nil {
		t.Fatal("Build is nil")
	}
	if spec.Build.Agent.Command != "claude" {
		t.Errorf("wrong command: %q", spec.Build.Agent.Command)
	}
	if len(spec.Build.Agent.Args) != 1 {
		t.Errorf("expected 1 arg, got %d", len(spec.Build.Agent.Args))
	}
	if spec.Build.Sandbox.Type != "docker" {
		t.Errorf("wrong sandbox type: %q", spec.Build.Sandbox.Type)
	}
	if spec.Build.Sandbox.Image != "ubuntu:22.04" {
		t.Errorf("wrong image: %q", spec.Build.Sandbox.Image)
	}
}

func TestGetTemplates(t *testing.T) {
	templates := GetTemplates()
	expected := []string{"basic", "web-api", "cli-tool"}
	for _, name := range expected {
		if _, ok := templates[name]; !ok {
			t.Errorf("missing template: %s", name)
		}
	}
}

func TestInitProject(t *testing.T) {
	dir := t.TempDir()
	outFile := filepath.Join(dir, "myapp.spec.promptc")

	if err := InitProject(outFile, "web-api"); err != nil {
		t.Fatalf("InitProject failed: %v", err)
	}

	data, err := os.ReadFile(outFile)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(data), "rest_api") {
		t.Error("web-api template missing rest_api import")
	}
}

func TestInitProject_AlreadyExists(t *testing.T) {
	dir := t.TempDir()
	outFile := filepath.Join(dir, "existing.spec.promptc")
	if err := os.WriteFile(outFile, []byte("content"), 0644); err != nil {
		t.Fatal(err)
	}

	err := InitProject(outFile, "basic")
	if err == nil {
		t.Fatal("expected error when file already exists")
	}
}

func TestInitProject_UnknownTemplate(t *testing.T) {
	dir := t.TempDir()
	outFile := filepath.Join(dir, "app.spec.promptc")

	err := InitProject(outFile, "nonexistent-template")
	if err == nil {
		t.Fatal("expected error for unknown template")
	}
}
