package tests

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"github.com/Geogboe/promptc/internal/builder"
	"github.com/Geogboe/promptc/internal/compiler"
)

func TestExamplesCompileToCommittedSnapshots(t *testing.T) {
	specFiles, err := filepath.Glob(filepath.Join("..", "examples", "*", "*.spec.promptc"))
	if err != nil {
		t.Fatalf("glob examples: %v", err)
	}
	if len(specFiles) == 0 {
		t.Fatal("no example specs found")
	}

	for _, specFile := range specFiles {
		t.Run(filepath.ToSlash(specFile), func(t *testing.T) {
			projectDir := filepath.Dir(specFile)
			comp := compiler.NewCompiler(projectDir)

			outPath, err := comp.Compile(specFile, nil)
			if err != nil {
				t.Fatalf("compile %s: %v", specFile, err)
			}

			got, err := os.ReadFile(outPath)
			if err != nil {
				t.Fatalf("read compiled output: %v", err)
			}

			wantPath := filepath.Join(projectDir, strings.TrimSuffix(filepath.Base(specFile), ".spec.promptc"), "instructions.promptc")
			want, err := os.ReadFile(wantPath)
			if err != nil {
				t.Fatalf("read committed snapshot %s: %v", wantPath, err)
			}

			if normalizeInstructionsSnapshot(string(got)) != normalizeInstructionsSnapshot(string(want)) {
				t.Fatalf("compiled output does not match committed snapshot: %s", wantPath)
			}
		})
	}
}

func TestBuildExampleDryRunFetchesResources(t *testing.T) {
	sourceSpec := filepath.Join("..", "examples", "03-build-with-agents", "codex.spec.promptc")
	rawSpec, err := os.ReadFile(sourceSpec)
	if err != nil {
		t.Fatalf("read source spec: %v", err)
	}

	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case "/prompting-playbook":
			w.Header().Set("Content-Type", "text/plain")
			_, _ = w.Write([]byte("Prompting playbook for support tooling"))
		case "/workflow-notes":
			w.Header().Set("Content-Type", "text/plain")
			_, _ = w.Write([]byte("Workflow notes for deterministic agent runs"))
		default:
			http.NotFound(w, r)
		}
	}))
	defer server.Close()

	replacements := strings.NewReplacer(
		"https://example.com/prompting-playbook", server.URL+"/prompting-playbook",
		"https://example.com/workflow-notes", server.URL+"/workflow-notes",
	)

	dir := t.TempDir()
	t.Setenv("LOCALAPPDATA", filepath.Join(dir, "localappdata"))
	specFile := filepath.Join(dir, "codex.spec.promptc")
	if err := os.WriteFile(specFile, []byte(replacements.Replace(string(rawSpec))), 0644); err != nil {
		t.Fatalf("write temp spec: %v", err)
	}

	if err := builder.Build(context.Background(), specFile, builder.BuildOptions{
		DryRun:  true,
		NoCache: true,
	}); err != nil {
		t.Fatalf("build dry run: %v", err)
	}

	outputDir := filepath.Join(dir, "codex")
	if _, err := os.Stat(filepath.Join(outputDir, "instructions.promptc")); err != nil {
		t.Fatalf("expected compiled instructions: %v", err)
	}

	for _, name := range []string{"prompting-playbook.md", "workflow-notes.md"} {
		path := filepath.Join(outputDir, "resources", name)
		data, err := os.ReadFile(path)
		if err != nil {
			t.Fatalf("read fetched resource %s: %v", name, err)
		}
		if len(strings.TrimSpace(string(data))) == 0 {
			t.Fatalf("resource %s is empty", name)
		}
	}
}

func normalizeInstructionsSnapshot(content string) string {
	lines := strings.Split(strings.ReplaceAll(content, "\r\n", "\n"), "\n")
	for i, line := range lines {
		switch {
		case strings.Contains(line, "Generated by promptc "):
			lines[i] = "  Generated by promptc <version>"
		case strings.Contains(line, "Compiled: "):
			lines[i] = "  Compiled: <timestamp>"
		}
	}

	normalized := strings.Join(lines, "\n")
	normalized = regexp.MustCompile(`\n+`).ReplaceAllString(normalized, "\n")
	return strings.TrimSpace(normalized)
}
