package formatter

import (
	"strings"
	"testing"
	"time"
)

func fixedMeta() FormatterMeta {
	return FormatterMeta{
		SpecFile:   "myapp.spec.promptc",
		Version:    "0.3.0",
		CompiledAt: time.Date(2026, 3, 19, 12, 0, 0, 0, time.UTC),
	}
}

func TestFormat_MetadataHeader(t *testing.T) {
	result := Format(Spec{}, "", fixedMeta())

	checks := []string{
		"Generated by promptc 0.3.0",
		"Source: myapp.spec.promptc",
		"Compiled: 2026-03-19T12:00:00Z",
		"Do not edit this file directly",
		"# Project Instructions",
	}
	for _, c := range checks {
		if !strings.Contains(result, c) {
			t.Errorf("missing expected content: %q", c)
		}
	}
}

func TestFormat_Context(t *testing.T) {
	spec := Spec{
		Context: map[string]interface{}{
			"language":  "go",
			"framework": "fiber",
		},
	}
	result := Format(spec, "", fixedMeta())

	if !strings.Contains(result, "## Context") {
		t.Error("missing Context section")
	}
	if !strings.Contains(result, "**language**: go") {
		t.Error("missing language context entry")
	}
	if !strings.Contains(result, "**framework**: fiber") {
		t.Error("missing framework context entry")
	}
}

func TestFormat_ContextSorted(t *testing.T) {
	spec := Spec{
		Context: map[string]interface{}{
			"framework": "fiber",
			"database":  "postgresql",
			"language":  "go",
		},
	}

	result := Format(spec, "", fixedMeta())

	databaseIndex := strings.Index(result, "**database**: postgresql")
	frameworkIndex := strings.Index(result, "**framework**: fiber")
	languageIndex := strings.Index(result, "**language**: go")

	if databaseIndex == -1 || frameworkIndex == -1 || languageIndex == -1 {
		t.Fatalf("missing expected context entries in output:\n%s", result)
	}
	if !(databaseIndex < frameworkIndex && frameworkIndex < languageIndex) {
		t.Fatalf("context entries are not sorted alphabetically:\n%s", result)
	}
}

func TestFormat_Guidelines(t *testing.T) {
	result := Format(Spec{}, "# REST API Patterns\nUse RESTful conventions.", fixedMeta())

	if !strings.Contains(result, "## Guidelines") {
		t.Error("missing Guidelines section")
	}
	if !strings.Contains(result, "REST API Patterns") {
		t.Error("missing import content in guidelines")
	}
}

func TestFormat_EmptyGuidelines(t *testing.T) {
	result := Format(Spec{}, "", fixedMeta())
	if strings.Contains(result, "## Guidelines") {
		t.Error("should not emit Guidelines section when imports are empty")
	}
}

func TestFormat_Features(t *testing.T) {
	spec := Spec{
		Features: []interface{}{
			map[string]interface{}{"auth": "JWT authentication"},
			"simple string feature",
		},
	}
	result := Format(spec, "", fixedMeta())

	if !strings.Contains(result, "## Features") {
		t.Error("missing Features section")
	}
	if !strings.Contains(result, "**auth**: JWT authentication") {
		t.Error("missing keyed feature")
	}
	if !strings.Contains(result, "simple string feature") {
		t.Error("missing string feature")
	}
}

func TestFormat_Constraints(t *testing.T) {
	spec := Spec{
		Constraints: []interface{}{
			"no_hardcoded_secrets",
			map[string]interface{}{"rate_limiting": "1000 req/min"},
			map[string]interface{}{"exclude": "some_lib"},
		},
	}
	result := Format(spec, "", fixedMeta())

	if !strings.Contains(result, "## Constraints") {
		t.Error("missing Constraints section")
	}
	if !strings.Contains(result, "No Hardcoded Secrets") {
		t.Error("missing title-cased constraint")
	}
	if !strings.Contains(result, "**Rate Limiting**: 1000 req/min") {
		t.Error("missing keyed constraint")
	}
	if strings.Contains(result, "exclude") {
		t.Error("exclude directive should not appear in output")
	}
}

func TestFormat_EmptySectionsOmitted(t *testing.T) {
	result := Format(Spec{}, "", fixedMeta())
	for _, section := range []string{"## Context", "## Guidelines", "## Features", "## Constraints"} {
		if strings.Contains(result, section) {
			t.Errorf("empty section %q should be omitted", section)
		}
	}
}

func TestTitleCase(t *testing.T) {
	tests := []struct {
		input string
		want  string
	}{
		{"no_hardcoded_secrets", "No Hardcoded Secrets"},
		{"comprehensive-test-coverage", "Comprehensive Test Coverage"},
		{"api", "Api"},
		{"already Title", "Already Title"},
	}
	for _, tt := range tests {
		got := titleCase(tt.input)
		if got != tt.want {
			t.Errorf("titleCase(%q) = %q, want %q", tt.input, got, tt.want)
		}
	}
}
