// Package formatter produces a single generic instructions.promptc output
// from a compiled spec. Output is model-agnostic markdown with a metadata header.
package formatter

import (
	"fmt"
	"slices"
	"strings"
	"time"
)

// Spec holds the structured data from a compiled .spec.promptc file.
type Spec struct {
	Context     map[string]interface{}
	Features    []interface{}
	Constraints []interface{}
}

// FormatterMeta contains metadata written into the output header comment.
type FormatterMeta struct {
	SpecFile   string    // path to source spec file
	Version    string    // promptc version string
	CompiledAt time.Time // compilation timestamp
}

// Format produces a generic instructions.promptc markdown string.
// The output contains a metadata header comment, followed by sections
// for Context, Guidelines (imported content), Features, and Constraints.
func Format(spec Spec, importsContent string, meta FormatterMeta) string {
	var b strings.Builder

	// Metadata header
	b.WriteString("<!--\n")
	fmt.Fprintf(&b, "  Generated by promptc %s\n", meta.Version)
	fmt.Fprintf(&b, "  Source: %s\n", meta.SpecFile)
	fmt.Fprintf(&b, "  Compiled: %s\n", meta.CompiledAt.UTC().Format(time.RFC3339))
	b.WriteString("  Do not edit this file directly — edit the spec and recompile.\n")
	b.WriteString("-->\n\n")

	b.WriteString("# Project Instructions\n")

	// Context section
	if len(spec.Context) > 0 {
		b.WriteString("\n## Context\n\n")
		keys := make([]string, 0, len(spec.Context))
		for key := range spec.Context {
			keys = append(keys, key)
		}
		slices.Sort(keys)
		for _, key := range keys {
			value := spec.Context[key]
			fmt.Fprintf(&b, "- **%s**: %v\n", key, value)
		}
	}

	// Guidelines section (resolved import content)
	if strings.TrimSpace(importsContent) != "" {
		b.WriteString("\n## Guidelines\n\n")
		b.WriteString(strings.TrimSpace(importsContent))
		b.WriteString("\n")
	}

	// Features section
	if len(spec.Features) > 0 {
		b.WriteString("\n## Features\n\n")
		for _, feature := range spec.Features {
			b.WriteString(formatFeatureItem(feature))
			b.WriteString("\n")
		}
	}

	// Constraints section
	if len(spec.Constraints) > 0 {
		b.WriteString("\n## Constraints\n\n")
		for _, constraint := range spec.Constraints {
			item := formatConstraintItem(constraint)
			if item != "" {
				b.WriteString(item)
				b.WriteString("\n")
			}
		}
	}

	return b.String()
}

func formatFeatureItem(item interface{}) string {
	switch v := item.(type) {
	case map[string]interface{}:
		for key, value := range v {
			return fmt.Sprintf("- **%s**: %v", key, value)
		}
	case string:
		return fmt.Sprintf("- %s", v)
	}
	return fmt.Sprintf("- %v", item)
}

func formatConstraintItem(item interface{}) string {
	switch v := item.(type) {
	case map[string]interface{}:
		for key, value := range v {
			if key == "exclude" {
				return "" // exclusion directives are not rendered
			}
			return fmt.Sprintf("- **%s**: %v", titleCase(key), value)
		}
	case string:
		if strings.TrimSpace(v) == "" {
			return ""
		}
		return fmt.Sprintf("- %s", titleCase(v))
	}
	return fmt.Sprintf("- %v", item)
}

// titleCase converts snake_case or kebab-case to Title Case.
func titleCase(s string) string {
	s = strings.ReplaceAll(s, "_", " ")
	s = strings.ReplaceAll(s, "-", " ")
	words := strings.Fields(s)
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}
